name: On main push

#on:
#  pull_request:
#    branches:
#      - main
#    types: [ closed ]

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: "Release"
    # Only run if the push was from release-please created PR but not from the tools/kysor branch
#    if: |
#      ${{ startsWith(github.event.pull_request.head.ref, 'release-please--branches--main') &&
#      github.event.pull_request.head.ref != 'release-please--branches--main--components--tools/kysor' }}
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
#        with:
#          token: ${{ secrets.RDK_ACTION }}
#          skip-github-pull-request: true
#      - name: ${{ steps.release.outputs.releases_created }}
#        run: echo "RELEASE_CREATED=${{ steps.release.outputs.releases_created }}"
#      - name: Release kysor
#        if: ${{ steps.release.outputs['tools/kysor--release_created'] }}
#        run: echo "RELEASE_CREATED=${{ steps.release.outputs['tools/kysor--release_created'] }}"

      # Checkout the repository
      - name: Checkout the repository
        if: ${{ steps.release.outputs['tools/kysor--release_created'] }}
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Release kysor
        if: ${{ steps.release.outputs['tools/kysor--release_created'] }}
        uses: ./.github/workflows/releases_go.yml
        with:
          working-dir: ${{ steps.release.outputs['tools/kysor--path'] }}
          version: ${{ steps.release.outputs['tools/kysor--version'] }}
          tag-name: ${{ steps.release.outputs['tools/kysor--tag-name'] }}

#      # Checkout the repository
#      - name: Checkout the repository
#        if: ${{ steps.release.outputs['tools/kysor--release_created'] }}
#        uses: actions/checkout@v4
#        with:
#          ref: main
#      # Setup Golang from working directory
#      - name: 🐿 Setup Golang
#        if: ${{ steps.release.outputs['tools/kysor--release_created'] }}
#        uses: actions/setup-go@v4
#        with:
##          go-version-file: 'tools/kysor/go.mod'
##          cache-dependency-path: 'tools/kysor/go.sum'
#          go-version-file: ${{ steps.release.outputs['tools/kysor--path'] }}/go.mod
#          cache-dependency-path: ${{ steps.release.outputs['tools/kysor--path'] }}/go.sum
#      # Build
#      - name: Build
#        if: ${{ steps.release.outputs['tools/kysor--release_created'] }}
#        run: make release
#        working-directory: ${{ steps.release.outputs['tools/kysor--path'] }}
#        env:
#          VERSION: ${{ steps.release.outputs['tools/kysor--version'] }}
#      # Upload Release Artifact
#      - name: Upload Release Artifact
#        if: ${{ steps.release.outputs['tools/kysor--release_created'] }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
##        working-directory: ${{ steps.release.outputs['tools/kysor--path'] }}
#        run: gh release upload ${{ steps.release.outputs['tools/kysor--tag-name'] }} ${{ steps.release.outputs['tools/kysor--path'] }}/release/*
