name: On main push

on:
  pull_request:
    branches:
      - main
    types: [ closed ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: "Release"
    # Only run if the push was from release-please created PR but not from the tools/kysor branch
    if: |
      ${{ startsWith(github.event.pull_request.head.ref, 'release-please--branches--main') && 
      github.event.pull_request.head.ref != 'release-please--branches--main--components--tools/kysor' }}
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RDK_ACTION }}
          skip-github-pull-request: true

  release-kysor:
    name: "Release Kysor"
    # Run only if the closed PR was from the tools/kysor branch
    if: |
      github.event_name == 'pull_request' &&
      github.event.action == 'closed' &&
      github.event.pull_request.base.ref == 'main' &&
      startsWith(github.event.pull_request.head.ref, 'release-please--branches--main--components--tools/kysor')
    with:
      working-dir: tools/kysor
    uses: ./.github/workflows/releases_go.yml
