name: On main push

#on:
#  pull_request:
#    branches:
#      - main
#    types: [ closed ]

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: "Release"
    # Only run if the push was from release-please created PR but not from the tools/kysor branch
#    if: |
#      ${{ startsWith(github.event.pull_request.head.ref, 'release-please--branches--main') &&
#      github.event.pull_request.head.ref != 'release-please--branches--main--components--tools/kysor' }}
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
#        with:
#          token: ${{ secrets.RDK_ACTION }}
#          skip-github-pull-request: true
      - name: ${{ steps.release.outputs.releases_created }}
        run: echo "RELEASE_CREATED=${{ steps.release.outputs.releases_created }}"
      - name: Release kysor
        if: ${{ steps.release.outputs['tools/kysor--release_created'] }}
        run: echo "RELEASE_CREATED=${{ steps.release.outputs['tools/kysor--release_created'] }}"

#      # Set working dir as env var
#      - name: Set working directory
#        if: ${{ steps.release.outputs['tools/kysor--release_created'] }}
#        run: echo "WORKING_DIR=${{ inputs.working-dir }}" >> $GITHUB_ENV
#      # Get version and save it to an environment variable
#      - name: Get ${{ inputs.working-dir }} version
#        if: ${{ steps.release.outputs['tools/kysor--release_created'] }}
#        run: echo "VERSION=$(cat .release-please-manifest.json | jq -r '.["'$WORKING_DIR'"]')" >> $GITHUB_ENV
      # Setup Golang from working directory
      - name: 🐿 Setup Golang
        if: ${{ steps.release.outputs['tools/kysor--release_created'] }}
        uses: actions/setup-go@v4
        with:
          go-version-file: ./tools/kysor/go.mod
          cache-dependency-path: ./tools/kysor/go.sum
#          go-version-file: ${{ steps.release.outputs['tools/kysor--path'] }}/go.mod
#          cache-dependency-path: ${{ steps.release.outputs['tools/kysor--path'] }}/go.sum
      # Build
      - name: Build
        if: ${{ steps.release.outputs['tools/kysor--release_created'] }}
        run: make release
        working-directory: ${{ steps.release.outputs['tools/kysor--path'] }}
        env:
          VERSION: ${{ steps.release.outputs['tools/kysor--version'] }}
      # Upload Release Artifact
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs['tools/kysor--release_created'] }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ steps.release.outputs['tools/kysor--path'] }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./release/*

#  release-kysor:
#    name: "Release Kysor"
#    # Run only if the closed PR was from the tools/kysor branch
#    if: |
#      github.event_name == 'pull_request' &&
#      github.event.action == 'closed' &&
#      github.event.pull_request.base.ref == 'main' &&
#      startsWith(github.event.pull_request.head.ref, 'release-please--branches--main--components--tools/kysor')
#    with:
#      working-dir: tools/kysor
#    uses: ./.github/workflows/releases_go.yml
