name: On main push

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    outputs:
      kysor-released: ${{ steps.release.outputs['tools/kysor--release_created'] }}
      kysor-path: ${{ steps.release.outputs['tools/kysor--path'] }}
      kysor-version: ${{ steps.release.outputs['tools/kysor--version'] }}
      kysor-tag-name: ${{ steps.release.outputs['tools/kysor--tag-name'] }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
      - name: Output kysor vars
        id: kysor-vars
        run: |
          echo "RELEASE_CREATED=${{ steps.release.outputs['tools/kysor--release_created'] }}"
          echo "PATH=${{ steps.release.outputs['tools/kysor--path'] }}"
          echo "VERSION=${{ steps.release.outputs['tools/kysor--version'] }}"
          echo "TAG_NAME=${{ steps.release.outputs['tools/kysor--tag-name'] }}"

  release-kysor:
    name: "Release kysor"
    needs: release
    if: ${{ needs.release.outputs.kysor-released }}
    uses: ./.github/workflows/releases_go.yml
    with:
      working-dir: ${{ needs.release.outputs.kysor-path }}
      version: ${{ needs.release.outputs.kysor-version }}
      tag-name: ${{ needs.release.outputs.kysor-tag-name }}